<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>08aa9c8e-bfb8-439c-be82-b5ef43c27b56</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to Not Metabolic Encephalopathy ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
