<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Down Payment Ratio Agent</name>
  <uuid>e12c1ceb-6cc4-4516-b472-0e26a14f3934</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[definitions
 set 'variable1' to an Answer List in 'Answer List' ; 
if 
	  variable1 is defined and the A5 - Car Price of variable1 does not equal 0 
then 
	set decision to round ((the A6 - Down Payment of variable1 / the A5 - Car Price of variable1),2) ;
else 
 set decision to null ; ]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
