<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>56e72ebd-d836-420a-867b-f490a0dd0f06</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to Not Applicable ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
