<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>2b3f3f4c-5480-4d4d-afda-cf08b94b84b0</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to Not Encephalopathy Not Otherwise Specified ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
