<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>69dd1982-e519-45a4-ba9b-82b2355166f7</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to - ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
