<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>All answered</name>
  <uuid>577778c1-dc35-4a36-8bc1-6122445c08b5</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	the Message of 'Intermediate Next Question' is not null 
then
	set decision to the Message of 'Intermediate Next Question' ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
