<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>c0adb484-c036-4486-8504-fe7afd2ec8d1</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to Not Medicare with Qualifying Secondary ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
