<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>24135e83-53ce-4a48-9d7f-ddc65b73b94f</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to Review Eligibility ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
