<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Distinct Decision</name>
  <uuid>0cc727b4-fa7a-4cf4-8315-7914a506a7cf</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to decision , made distinct;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
