<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Distinct Function</name>
  <uuid>d740e1e4-4caa-4fde-bf14-214ff7973539</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if 
	decision are defined 
then
   set decision to decision , made distinct ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
