<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Policy Copay</name>
  <uuid>db6a06d6-30a5-4623-bd83-4faa01c310d2</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to the policy copay computed from
		Policy being Policy , 
		Order being Order , 
		Payer being Payer , 
		Policy Activity being 'Policy Activity' ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
