<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>fe582e80-b145-4ad8-a82f-82253623fa1b</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[add 1/1/1900 to decision ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
