<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>00b6e510-154d-4c75-a3ff-4c9bf2c06033</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to Not Applicable ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
