<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>229b35d0-72ae-46a9-ab18-35fe4a7931d5</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[add - to decision ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
