<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Distinct Function</name>
  <uuid>3ac4ecbf-565d-4856-8aba-167144992150</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to decision , made distinct; ]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
