<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Policy Total Price rule</name>
  <uuid>c8e4d054-84d7-4b20-916e-0cbde6066bc7</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[definitions
 set 'Year 1 and 2 price output' to the year 1 and 2 price computed from 
	Payer being Payer , 
	Order being Order , 
	Network being Network , 
	Policy being Policy , 
	Terms being Terms , 
	System being System , 
	Patient being Patient , 
	State being State , 
	Policy Activity being 'Policy Activity' , 
	HCPCS Biling being 'HCPCS Biling' ; 
if 
	'Year 1 and 2 price output' is defined 
then  
    set decision to ( the Year 1 Price of 'Year 1 and 2 price output' + the Year 2 Price of 'Year 1 and 2 price output' ) ;
else
	set decision to 0 ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
