<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>9508ef5f-c26b-4f33-93ae-6587c11b220a</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to - ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
