<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>6b43d417-d94e-4a0d-b3b4-e8bcdb91b1be</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to Not Rapidly Progressive Skin Wound ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
