<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>ba97efd5-e0f4-40b9-8c2c-7553853a31d1</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to Valid ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
