<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>77994a54-c6b1-4976-9020-60b67d3c1a93</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[add a new Next Best Action where
		the Actions is Stop Application , 
		the Message is "-" to decision ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
