<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>dc83b7f1-448c-42fe-8127-fedcc293fc9a</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to Unavailable ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
