<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>d8e059ae-74db-4df2-b33e-e8135e9e0da6</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to Not Medicare HN ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
