<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>245465c9-6ac1-49a7-91e2-d8f766c30229</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[add "-" to decision ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
