<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Down Payment Ratio</name>
  <uuid>a49d4c0c-c2ee-4d85-ba4c-db2959261818</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to  round((the cardownpayment of Application / the msrp of Asset), 2);]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
