<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>b1a2bce8-fbbb-43d8-a979-3ea3179cc418</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to Unavailable ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
