<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Pursued Policy Output</name>
  <uuid>bc272b72-dde0-4bfc-a9ba-6f4769b25cba</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to the pursued policy computed from
		Policy being Policy , 
		Order being Order ; ]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
