<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Full Results For Year 1 and 2 Price</name>
  <uuid>ac9a91ab-d1f4-4259-93b1-a0b3c29ce8ed</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to a new Year 1 and 2 Price service where
		the Year 1 Price is 'Year 1 Price' , 
		the Year 2 Price is 'Year 2 Price' ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
