<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>77e537af-0148-4377-b723-b8e0a303d930</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to a new Year 1 and 2 Price service where
		the Year 1 Price is -1, 
		the Year 2 Price is -1;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
