<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>c40979d6-4a38-4e09-a10d-b2c036d0cda6</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to a new Applicant Credit History Recommended Outcome Service where
 
		the Application Credit History Recommended Outcome is 'Application Credit History Recommended Outcome' ;
	]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
