<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Policy Months Remaining</name>
  <uuid>047e5dcc-c4bc-4eab-a3d5-7358392c2233</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
 'Set Renewal Date' is not null and System is not null
then
 set decision to the number of months between 'Set Renewal Date' and the Current Date of System ;
else
 set decision to 0 ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
