<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>354f95b5-8890-4bf2-819b-5ea54b9b7697</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to null ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
