<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>341b2830-9128-4ee7-b478-13be90387f32</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to Not Heart Failure ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
