<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>912ae04b-2471-4b10-84ad-b4e91048ed74</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[add a new Ranking Output where
		the Message is "-" , 
		the Question is - , 
		the A Ranking is 100 to decision ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
