<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Distinct Function</name>
  <uuid>b11ffbcf-98c8-4bba-ac2b-05512c0f2768</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to decision , made distinct;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
