<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Stop Application Check</name>
  <uuid>82121897-4989-46ab-895a-82077e0ce32b</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[definitions
 set 'variable1' to a Next Best Action in 'Next Best Actions';
if 
	 the Actions of variable1 is Stop Application 
then
	 set decision to a new Stop Application Check where 
	 Stop Application is true, 
	No Stop Application is false ;
else 
	set decision to a new Stop Application Check where  
	No Stop Application is true, 
	Stop Application is false ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
