<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>97855b2f-e90d-42d0-b222-fe32c9e3bcf0</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to Not Failure ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
