<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>1351ddf6-6040-4d3f-93b5-0e27af5e4e2f</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to Not Medicare with Qualifying Secondary ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
