<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>default-value-setting</name>
  <uuid>4111218f-ec49-4a55-b9f0-f3bed40c3df8</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[add a new Policy where
		the DME Maximum is 0 , 
		the Active Policy is Not Active , 
		the Bill to Payer ID is "-" , 
		the Customer Purchase Order is "-" , 
		the Network ID is "-" , 
		the Payer is "-" , 
		the Payer Bucket is "-" , 
		the Payer ID is "-" , 
		the Payer Name is "-" , 
		the Payer Type is "-" , 
		the Plan Designation is "-" , 
		the Plan Type is "-" , 
		the Policy Activity is "-" , 
		the Policy ID is "-" , 
		the Renewal Date is 9/24/2025 , 
		the Secondary No Pay is Secondary Pay , 
		the Policy State is "-" to Policy ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
