<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Expenses Ratio</name>
  <uuid>30e6cda1-5478-4e01-b2be-dcea5954128d</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to  round((the tdsExpenses of Application / the submittedIncome of Application), 2);
]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
