<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>a64d94ed-1cf0-466a-92bb-42456b93afb6</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to null ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
