<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>acb1be93-f21e-407c-84fb-c10722744bd9</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to Not Aspiration Syndrome ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
