<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>18a0808f-441a-4f7b-9119-10cbe8477482</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to Acceptable ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
