<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>7323b57d-d9cd-4eaa-b7a7-e9e33a218f42</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to <a number> ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
