<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>f26cd902-a758-4b87-803a-97f5bc22c8c8</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to null ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
