<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>a9fa8b59-a172-434d-a3da-abce044e5182</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to Not Discounted ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
