<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>9efb7cb5-3ab0-4fe8-a22e-ccb6db3f11c7</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to Not Self Pay ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
