<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Policy Benefit Level Output</name>
  <uuid>46c7ef1a-3272-4cc0-855a-20b95b30ed3a</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to the policy benefit levels computed from
		Policy Activity being 'Policy Activity' , 
		Policy being Policy , 
		Payer being Payer ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
