<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>562b0d15-ae73-4c84-bb0d-fc3d9f462956</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to No Functional Decline ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
