<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>1f80d93e-8ad7-4642-aef5-b4d5ccb491a4</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to Not Acute Respiratory Failure ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
