<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Applications Credit Risk Tier</name>
  <uuid>10c645e4-86f1-4d85-8c1f-2530462b27b5</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[definitions 
	set 'aCustomer' to all Customers in Customer ;
    
	set 'variable2' to all Tiers in 'Applicant Credit Risk Tier' ; 
     
     
   if aCustomer  are defined  and  the number of elements in aCustomer  ≥  1 
    then 
	define 'variable1' as the number of elements in aCustomer ; 
    
   for each number in the range from 1 to variable1,
   where  the customerType of  the element at the position corresponding to each number in aCustomer is "Primary"     : 
   -  add the element at the position corresponding to this number in variable2 to decision; ]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
