<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>First Index Value</name>
  <uuid>b37fdef8-7584-42c2-86c6-e4bdca2573f4</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[ set decision to { the first element in decision } ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
