<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>54ab24a3-bc1b-4357-9da7-00ced744ee1b</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to Not Anoxic Brain Injury ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
