<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>7aab9a58-525a-4b46-9024-958c90604106</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to Restricted ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
