<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>8670d0a4-9123-4148-9df3-442413763e31</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to Acceptable ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
