<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>c41392b5-21f5-4a53-8e81-c0c05c1b8680</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to Not Medicare with Qualifying Secondary ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
