<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Calculate Allowables</name>
  <uuid>bae0a24d-f0dd-4265-bebe-6d3263ab67d0</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if 
	'Line Item Unit Allowables' are defined
then
	 set decision to the sum of the Line Item Unit Allowables of 'Line Item Unit Allowables' ;
else
	 set decision to 0 ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
