<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>TDSR Balance Obligation Monthly Payment Amount</name>
  <uuid>9d4896d9-2e49-4892-8a01-1e6e44b72fac</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[definitions 
	set 'variable2' to all Customers in Customer ; 
    
	set 'variable3' to all Debts in the Debts of variable2; 
    
    
if
   'TDSR Trade Obligation Factor' are defined and the number of elements in 'TDSR Trade Obligation Factor' ≥ 1 then 
	define 'variable1' as the number of elements in  'TDSR Trade Obligation Factor' ; 
    for each number in the range from 1 to variable1 : 
	- add the element at the position corresponding to this number in  'TDSR Trade Obligation Factor'
    * the balAmt of the element at the position corresponding to this number in variable3 to decision ; ]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
