<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>a2abf9be-b402-48fe-9d7b-392f7fa81f05</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to a new Application Action where
		the Message is "Continue" , 
		the Reason is "-" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
