<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>c056b0a3-f3b3-491d-b102-3041820c12b2</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[add a new HCPCS Quantity where
		the Location is - , 
		the Quantity is -1 to decision ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
