<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Distinct Function</name>
  <uuid>9dd8eb6c-00d9-484f-acb9-01814f13df9e</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[ set decision to decision , made distinct , sorted by Output then by Message ; ]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
