<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>44a0bf16-42f3-4dff-bd27-86ee07c7697b</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to Unavailable ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
