<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Full Results For Year 1 and 2 Coinsurance</name>
  <uuid>661e5e7f-e850-4865-8438-c445d17fe031</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to a new Yearly Coinsurance service where
		the Year 1 Coinsurance is 'Year 1 Coinsurance' , 
		the Year 2 Coinsurance is 'Year 2 Coinsurance' ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
