<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>efe1c7ef-d439-4939-9fa5-311aafdf1221</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[add 1/1/1900 to decision ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
