<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>0cb6959f-280e-47c0-a7ae-ad23e0360179</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to -1 ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
