<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Order Year 2 Months to Bill</name>
  <uuid>025a8080-e55f-4408-944d-543128cfd685</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to a new Payment Terms Output where  
	the Order Year 2 Months to Bill is the Order Year 2 Months to Bill of Full Results For Calculate Payment Terms of the calculate payment terms computed from 
	Payer being Payer , 
	Order being Order , 
	Network being Network , 
	Policy being Policy , 
	Terms being Terms , 
	System being System , 
	Patient being Patient , 
	State being State , 
	Policy Activity being 'Policy Activity' , 
	HCPCS Biling being 'HCPCS Biling' ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
