<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>bc228cb1-4b07-4e7e-8707-ea2fa7ed6d52</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to Not Sepsis ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
