<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>293d5ba9-c19a-47a6-886d-448fe143b639</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to 1;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
