<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Difference in ADL Level</name>
  <uuid>f5b17b24-ae25-4d9c-b327-1ff14ececd4e</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to a copy of decision where the Difference in ADL is the Current ADL Level of decision - the Previous ADL Level of decision; ]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
