<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>a2506db1-667d-41c6-9058-87808681483b</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to Manual Review ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
