<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Durable Medical Equipment Maximum</name>
  <uuid>a647087f-a961-403d-b360-866d80a7d608</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to the Durable Medical Equipment Maximums of the yearly out of pocket left computed from 
	Payer being Payer , 
	Order being Order , 
	Policy being Policy , 
	Policy Activity being 'Policy Activity' ; ]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
