<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Down Payment Ratio</name>
  <uuid>2a42a68e-6a4e-4c3c-a55c-94d364e5e68c</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[ if 
	the cardownpayment of Application ≠  0 and the msrp of Asset  ≠ 0 
then

set decision to  round((the cardownpayment of Application / the msrp of Asset), 2);

else 
	set decision to 00; ]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
