<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Year 1 Out of Pocket Left</name>
  <uuid>bae40544-08c3-40ad-a372-db888f6f9629</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to the Year 1 Out of Pocket Left of the yearly out of pocket left computed from 
	Payer being Payer , 
	Order being Order , 
	Policy being Policy , 
	Policy Activity being 'Policy Activity' ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
