<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>91916648-bab8-44ef-ba07-1ca49bed694b</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[add No Debt Problem to decision ; ]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
