<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Expenses Ratio</name>
  <uuid>0d3137ec-1e25-4ad1-a7cc-80828503222c</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if 
the tdsExpenses of Application ≠ 0 and the tdsExpenses of Application ≠ 0 then
set decision to  round((the tdsExpenses of Application / the submittedIncome of Application), 2);
else set decision to  00
;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
