<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Difference in Feeding ADL Level</name>
  <uuid>3f55d10d-acb7-4c13-8a1f-f545a0dbb428</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to a copy of decision where the Difference in ADL is the Current ADL Level of decision - the Previous ADL Level of decision; ]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
