<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>a7b4a55a-0853-46e1-aa1c-707ce5c9b74f</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to Not VA ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
