<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Final Service</name>
  <uuid>4d6c68e3-ce36-4e68-be8f-3b686806a612</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to a new Application PreBureau Eligibility Service where 
		the Applicant Age Acceptabilities are 'Applicant Age Acceptability' , 
		the Applicant Eligibilities are 'Applicant Eligibility' , 
		the Applicant Employment Acceptabilities are 'Applicant Employment Acceptability' , 
		the Applicant Location Acceptabilities are 'Applicant Location Acceptability' , 
		the Applicant Submitted Income Acceptability is 'Applicant Submitted Income Acceptability' , 
		the Application PreBureau Eligibility is 'Application PreBureau Eligibility service'  ; ]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
