<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>7da77c38-3097-45b5-a17d-2de58e13157c</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to null ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
