<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>168c54c6-47b1-42ce-9db3-5e1da60c5768</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to Not Use IPA ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
