<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>b282ad09-80d8-415d-af86-d6d69af4089a</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to Acceptable ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
