<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>d5b84e62-39ef-44e4-9c8b-c50279cba8d4</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to Not Applicable ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
