<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Policy Benefit Level Output</name>
  <uuid>47d684f6-7b38-455a-980f-01a3e48a7d96</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to the policy benefit levels computed from
		Policy Activity being 'Policy Activity' , 
		Policy being Policy , 
		Payer being Payer ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
