<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Full Results For Year 1 and 2 Out of Pocket Left</name>
  <uuid>6d3077c2-fc18-46dc-8a43-aecb22551015</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to a new Yearly Out of Pocket Left service where
		the Year 1 Out of Pocket Left is 'Year 1 Out of Pocket Left' , 
		the Year 2 Out of Pocket Left is 'Year 2 Out of Pocket Left' , 
		the Durable Medical Equipment Maximums are 'Durable Medical Equipment Maximum' ; ]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
