<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Distinct Function</name>
  <uuid>ec397fcf-0c37-49c2-85fd-31f095430f3a</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to decision , made distinct; ]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
