<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>196351ab-034c-4f9c-9348-d576502dccfd</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to - ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
