<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>d667a64f-dae3-48f6-bf67-251adff69166</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to Unavailable ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
