<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Shipping Price</name>
  <uuid>e722e99f-a7c6-45e2-bf68-e77374d8c2d3</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to round('Price Before Discount' * (1 - 'Customer Discount'), 2) ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
