<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>68ceaec8-e7ea-4e0d-a4d1-771c03363bcf</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to Not Eligible ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
