<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Decision</name>
  <uuid>9cece7c7-34c3-4618-ad6f-ebce45c9c98c</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	the Controller Part Number of Input is not empty 
then
	set decision to "Working" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
