<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>TestRule</name>
  <uuid>2bd3ae5d-177b-4588-8747-dd1867b40646</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	the Distance In Miles of Shipment1 is at least <min> and less than <max>
	and the Size of Shipment1 is <a Size Enums>
then
	set decision to <a number> ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
