<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>c4dcdf1e-347c-4e4a-8637-b7b635691b27</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to -1;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
