<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Skip</name>
  <uuid>338b3f61-16e6-4dba-bbc8-3442021e42b1</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to decision , skipping the first 1 elements ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
