<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>1a247443-b963-44f0-8064-d3377db435e6</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[add _ to decision ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
