<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Trade Equivalent Monthly Payment Amount</name>
  <uuid>8b9397b2-b10b-40eb-8c54-8ca1aa7400cb</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[definitions 
	set 'variable1' to all Customers in Customer ;
if 
'Trade Payment Frequency'  are defined and the number of elements in 'Trade Payment Frequency' ≥  1
then 
define 'variable2' as 'Trade Payment Frequency';
define 'variable3' as the number of elements in variable2 ;
 for each number in the range from 1 to variable3 : 
	- add (the tradePmtAmt of the TransUnion Report of the Credit Bureau Report of the element at the position corresponding to this number in variable1 
    * the element at the position corresponding to this number  in variable2 )/12 to decision ; ]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
