<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>c4a7fcfb-34ca-4493-bd98-315b35304481</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to Not Medicare ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
