<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Policy Months Remaining</name>
  <uuid>bba75426-e009-433d-bbc7-53f1d4737936</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to the policy months remaining computed from 
	Payer being Payer , 
	Order being Order , 
	Policy being Policy , 
	System being System ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
