<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>bedef4a7-deb2-49b9-aa17-c6ee9839dc4f</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to Not Medicare or Medicaid ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
