<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>a189e9a6-584c-48dd-bb57-a1d706d17749</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to Not Medicare with Qualifying Secondary ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
