<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Distinct Function</name>
  <uuid>d27fb56a-e546-42b2-9b2a-e24966c116d8</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to decision , made distinct ; ]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
