<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>7b33c6b4-ed94-4657-9e1c-618195e7d3a8</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to -1 ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
