<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>de132853-fa03-4f62-bf69-0dcaa4986f60</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to a new Policy Expired where
		the Message is "The policy has expired. Please review the plan renewal date" , 
		the Policy Expired Value is Expired ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
