<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>0fae3287-bd76-4d5b-a69a-f2eea7e83883</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to Not Renal Failure ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
