<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>a10ac21a-7c38-4192-9a3f-c57710190fe5</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to Not Medicare with Qualifying Secondary ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
