<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Factor Decline Ranking</name>
  <uuid>245c799b-089b-4778-91b0-e409eede02ef</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[definitions
 set 'variable1' to a Ranking Output in 'Agent Decline Ranking' ;
then
	 add a new Ranking Output where
      the Question is the Question of variable1 , 
      the A Ranking is the A Ranking of variable1 * 1.2 to decision ;
]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
