<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>fb0acf3e-04f9-47c3-b787-768aba1a808a</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to Not Highly Aggressive ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
