<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Applicant Age</name>
  <uuid>84ccd394-23bb-4b0a-b01d-8a1cf9466f6c</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to the number of years between the requestDate of Application and  the dateOfBirth of  Customer ; ]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
