<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Year 2 Price</name>
  <uuid>603753b3-4b62-4631-a05b-6079a3e3fcfe</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to the Year 2 Price of the year 1 and 2 price computed from 
	Payer being Payer , 
	Order being Order , 
	Network being Network , 
	Policy being Policy , 
	Terms being Terms , 
	System being System , 
	Patient being Patient , 
	State being State , 
	Policy Activity being 'Policy Activity' , 
	HCPCS Biling being 'HCPCS Biling' ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
