<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Application PreBureau Eligibility</name>
  <uuid>d9891d2d-1067-419a-9a75-94de8c76455e</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[definitions 
	set 'an Applicant Eligibility' to an Eligible/Not Eligible in the Outputs of 'Applicant Eligibility'  ; 
if
	'an Applicant Eligibility' is one of { Not Eligible } 
then
	set decision to  Not Eligible ;
     
else 
 set decision to  Eligible ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
