<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>a25bc4af-0889-4fd3-8e85-7a2dcd3baa9f</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[add Not Pathology Aggressive to decision ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
