<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Distinct</name>
  <uuid>131a3b5f-f502-457e-9994-6e673e7fd291</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to decision , made distinct;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
