<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>b6b8daf9-e30b-4815-81b6-1a0225a61234</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[add " " to decision ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
