<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Difference in Toileting ADL Level</name>
  <uuid>9c39d218-685f-461a-9c86-af8088460890</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to a copy of decision where the Difference in ADL is the Current ADL Level of decision - the Previous ADL Level of decision; ]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
